# Generated by Django 4.1.4 on 2023-04-15 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='shop_images/')),
                ('qrcode', models.ImageField(default='', upload_to='shop_qrcodes/')),
                ('user', models.OneToOneField(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Kitchen', 'Home appliance'), ('Cloths', 'Shoes'), ('electricals', 'non electric')], max_length=254, null=True)),
                ('brand', models.CharField(max_length=254)),
                ('barcode', models.CharField(default=False, max_length=100, unique=True)),
                ('description', models.CharField(max_length=254)),
                ('picture', models.ImageField(default='', upload_to='prodimg')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Kitchen', 'Home appliance'), ('Cloths', 'Shoes'), ('electricals', 'non electric')], max_length=254, null=True)),
                ('brand', models.CharField(default='', max_length=254)),
                ('quantity', models.CharField(default='', max_length=254)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
