# Generated by Django 4.1.4 on 2023-03-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Kitchen', 'Home appliance'), ('Cloths', 'Shoes'), ('electricals', 'non electric')], max_length=254, null=True),
        ),
    ]
