# Generated by Django 4.1.4 on 2023-04-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_shop_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shop',
        ),
    ]
