# Generated by Django 4.1.4 on 2023-04-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_cart_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
