# Generated by Django 4.1.4 on 2023-04-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
