# Generated by Django 4.1.4 on 2023-03-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_item_brand_item_category_item_quantity_item_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shop'),
        ),
    ]
