# Generated by Django 4.1.4 on 2023-04-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_item_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='qrval',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
