# Generated by Django 4.1.4 on 2023-04-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_cart_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shop',
        ),
    ]
