# Generated by Django 4.1.4 on 2023-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_shop_qrval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='description',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='prodimg'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='qrval',
            field=models.CharField(default='', max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
