# Generated by Django 4.1.4 on 2023-04-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_quantity_product_description_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shop'),
        ),
    ]
