# Generated by Django 4.1.4 on 2023-04-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_cart_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.shop'),
        ),
    ]
