# Generated by Django 4.1.4 on 2023-04-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_product_shop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
