# Generated by Django 4.1.4 on 2023-05-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_quantity_item_description_remove_item_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.shop'),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Kitchen', 'Home appliance'), ('Cloths', 'Shoes'), ('electricals', 'non electric')], default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
        ),
    ]
