# Generated by Django 4.1.4 on 2023-05-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_description_item_quantity_remove_item_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=254)),
                ('brand', models.CharField(default='', max_length=254)),
                ('quantity', models.CharField(default='', max_length=254)),
                ('barcode', models.CharField(default='', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('shop', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.shop')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
