# Generated by Django 4.1.4 on 2023-04-11 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_cart_added_at_cart_barcode_cart_shop_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='user.shop'),
        ),
    ]
