# Generated by Django 4.1.4 on 2023-04-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_cart_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_at',
        ),
    ]
