# Generated by Django 4.1.4 on 2023-04-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_cart_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='barcode',
            field=models.CharField(default='000000000001', max_length=100, unique=True),
        ),
    ]
