# Generated by Django 4.1.4 on 2023-04-11 01:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_alter_cart_barcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart_item',
        ),
    ]
