# Generated by Django 4.1.4 on 2023-04-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_cart_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='added_at',
        ),
    ]
