# Generated by Django 4.1.4 on 2023-04-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_cart_delete_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_at',
        ),
    ]
