# Generated by Django 4.1.4 on 2023-04-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_cart_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='barcode',
            field=models.CharField(default='1', max_length=100, unique=True),
        ),
    ]
