# Generated by Django 4.1.4 on 2023-04-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_cart_barcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default='shop', on_delete=django.db.models.deletion.CASCADE, to='user.product'),
        ),
    ]
