# Generated by Django 4.1.4 on 2023-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_cart_unique_together_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='barcode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
