# Generated by Django 4.1.4 on 2023-04-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_product_barcode_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Barcode',
        ),
    ]
