# Generated by Django 4.1.4 on 2023-04-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_product_barcode_delete_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='shop',
            new_name='shop_d',
        ),
    ]
