# Generated by Django 4.1.4 on 2023-04-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_rename_shop_d_cart_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shop'),
        ),
    ]
