# Generated by Django 4.1.4 on 2023-04-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_cart_product_alter_cart_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='prod',
        ),
    ]
