# Generated by Django 4.1.4 on 2023-04-12 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0030_rename_product_cart_prod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='prod',
            new_name='product',
        ),
    ]
